//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManagement.DAO
{
    using System.Linq;
    using System.Collections.Generic;
    
    public partial class ShiftTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShiftTime()
        {
            this.ShiftRegistrations = new HashSet<ShiftRegistration>();
        }
    
        public string WeekDay { get; set; }
        public int Shift { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiftRegistration> ShiftRegistrations { get; set; }


        public static List<ShiftTime> getAllShift(){
            using ( var context = new StoreManagementEntities() ) {
                return context.ShiftTimes.ToList();
            }
        }

        public static void resetShift(){
            using ( var context = new StoreManagementEntities() ) {
                foreach ( var shift in context.ShiftTimes ) {
                    shift.Status = 1;
                }

                context.SaveChanges();
            }
        }

        public override string ToString(){
            string str = $"(WeekDay : {WeekDay} - Shift : {Shift} - Status : {Status})";

            return str;
        }
    }
}
